# Generated by Django 5.1.5 on 2025-02-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_image'),
    ]

    operations = [
    ]
